"""
Classroom Optimization & Dynamic Lecture Merging System
-------------------------------------------------------
This module uses real-time attendance & occupancy data generated by the face verification
pipeline to dynamically identify low-attendance parallel/compatible classes and optimize
classroom allocation through dynamic lecture merging.
"""

import datetime
from dataclasses import dataclass, field
from typing import List, Dict, Optional, Tuple

@dataclass
class Classroom:
    room_id: str
    capacity: int
    has_projector: bool = True
    is_available: bool = True

@dataclass
class LectureSession:
    session_id: str
    subject: str
    faculty: str
    division: str
    room_id: str
    start_time: str
    end_time: str
    registered_students: int
    present_students: int = 0

    @property
    def attendance_rate(self) -> float:
        if self.registered_students == 0:
            return 0.0
        return (self.present_students / self.registered_students) * 100.0

@dataclass
class MergeRecommendation:
    merged_session_ids: List[str]
    subject: str
    combined_divisions: List[str]
    target_room: str
    freed_rooms: List[str]
    total_students: int
    room_capacity: int
    assigned_faculty: str
    time_slot: str
    energy_savings_kWh_est: float

class DynamicLectureMerger:
    def __init__(self, attendance_threshold: float = 30.0):
        self.attendance_threshold = attendance_threshold
        self.rooms: Dict[str, Classroom] = {}
        self.sessions: Dict[str, LectureSession] = {}

    def add_classroom(self, room_id: str, capacity: int, has_projector: bool = True):
        self.rooms[room_id] = Classroom(room_id, capacity, has_projector)

    def add_session(self, session: LectureSession):
        self.sessions[session.session_id] = session

    def update_session_attendance(self, session_id: str, present_count: int):
        if session_id in self.sessions:
            self.sessions[session_id].present_students = present_count

    def find_merge_candidates(self) -> List[LectureSession]:
        candidates = []
        for session in self.sessions.values():
            if session.attendance_rate < self.attendance_threshold:
                candidates.append(session)
        return candidates

    def optimize_allocations(self) -> Tuple[List[MergeRecommendation], List[str]]:
        candidates = self.find_merge_candidates()
        recommendations: List[MergeRecommendation] = []
        visited_session_ids = set()

        # Group candidates by Subject and Time Slot
        grouped_candidates: Dict[Tuple[str, str], List[LectureSession]] = {}
        for s in candidates:
            key = (s.subject, f"{s.start_time}-{s.end_time}")
            grouped_candidates.setdefault(key, []).append(s)

        freed_classrooms: List[str] = []

        for (subject, time_slot), session_group in grouped_candidates.items():
            if len(session_group) < 2:
                continue  # Need at least 2 sessions to merge

            total_present = sum(s.present_students for s in session_group)
            
            # Find best target room among current rooms or available larger rooms
            current_rooms = [s.room_id for s in session_group]
            
            # Candidate target rooms sorted by capacity (smallest suitable room first)
            suitable_rooms = sorted(
                [r for r in self.rooms.values() if r.capacity >= total_present],
                key=lambda r: r.capacity
            )

            if not suitable_rooms:
                print(f"[OPTIMIZER WARN] No room large enough for combined {total_present} students in {subject}.")
                continue

            target_room = suitable_rooms[0]

            # Choose primary faculty (e.g. session with highest attendance or first)
            primary_session = max(session_group, key=lambda s: s.present_students)
            assigned_faculty = primary_session.faculty

            freed = [s.room_id for s in session_group if s.room_id != target_room.room_id]
            freed_classrooms.extend(freed)

            rec = MergeRecommendation(
                merged_session_ids=[s.session_id for s in session_group],
                subject=subject,
                combined_divisions=[s.division for s in session_group],
                target_room=target_room.room_id,
                freed_rooms=freed,
                total_students=total_present,
                room_capacity=target_room.capacity,
                assigned_faculty=assigned_faculty,
                time_slot=time_slot,
                energy_savings_kWh_est=len(freed) * 1.5  # Estimated 1.5 kWh saved per freed room/hour
            )

            recommendations.append(rec)
            for s in session_group:
                visited_session_ids.add(s.session_id)

        return recommendations, freed_classrooms

    def generate_notifications(self, recommendations: List[MergeRecommendation]) -> Dict[str, List[str]]:
        notifications = {
            "faculty": [],
            "students": [],
            "admin": []
        }

        for rec in recommendations:
            divs_str = ", ".join(rec.combined_divisions)
            freed_str = ", ".join(rec.freed_rooms)

            # Faculty notification
            notifications["faculty"].append(
                f"[FACULTY NOTIFICATION] {rec.assigned_faculty}: Your {rec.subject} lecture for Divisions ({divs_str}) "
                f"at {rec.time_slot} is MERGED into Room {rec.target_room}."
            )

            # Student notification
            notifications["students"].append(
                f"[STUDENT NOTIFICATION] Attention Divisions {divs_str}: {rec.subject} lecture at {rec.time_slot} "
                f"is shifted to Room {rec.target_room} due to dynamic scheduling."
            )

            # Admin notification
            notifications["admin"].append(
                f"[ADMIN / FACILITIES] Room(s) {freed_str} VACATED at {rec.time_slot}. "
                f"Estimated energy saved: {rec.energy_savings_kWh_est:.1f} kWh. HVAC & Lighting powering off."
            )

        return notifications


def run_demo_optimization(live_attendance_count: int = 15) -> Dict:
    """
    Demo function that simulates a multi-classroom schedule scenario
    and runs the dynamic merging optimization.
    """
    merger = DynamicLectureMerger(attendance_threshold=35.0)

    # 1. Register Classrooms
    merger.add_classroom("Room A101", capacity=60)
    merger.add_classroom("Room A102", capacity=60)
    merger.add_classroom("Room B201", capacity=120)
    merger.add_classroom("Room C301", capacity=80)

    # 2. Register Today's Sessions (10:00 AM - 11:00 AM)
    # Division A: Data Structures (Registered 60, Live Attendance simulated or passed)
    merger.add_session(LectureSession(
        session_id="SESS_01",
        subject="Data Structures",
        faculty="Dr. Sharma",
        division="Div-A",
        room_id="Room A101",
        start_time="10:00",
        end_time="11:00",
        registered_students=60,
        present_students=live_attendance_count  # From face verification pipeline
    ))

    # Division B: Data Structures (Registered 60, Low Attendance = 18 students / 30%)
    merger.add_session(LectureSession(
        session_id="SESS_02",
        subject="Data Structures",
        faculty="Prof. Verma",
        division="Div-B",
        room_id="Room A102",
        start_time="10:00",
        end_time="11:00",
        registered_students=60,
        present_students=18
    ))

    # Division C: Computer Networks (Registered 60, High Attendance = 52 students / 86%)
    merger.add_session(LectureSession(
        session_id="SESS_03",
        subject="Computer Networks",
        faculty="Dr. Kulkarni",
        division="Div-C",
        room_id="Room C301",
        start_time="10:00",
        end_time="11:00",
        registered_students=60,
        present_students=52
    ))

    # 3. Run Optimization Engine
    recs, freed_rooms = merger.optimize_allocations()
    notifs = merger.generate_notifications(recs)

    print("\n" + "="*70)
    print("=== DYNAMIC CLASSROOM LECTURE MERGING SYSTEM RESULT ===")
    print("="*70)
    print(f"Attendance Threshold: {merger.attendance_threshold}%")
    print("\nCurrent Session Status:")
    for s in merger.sessions.values():
        status = "LOW ATTENDANCE (MERGE CANDIDATE)" if s.attendance_rate < merger.attendance_threshold else "NORMAL"
        print(f" - [{s.session_id}] {s.subject} ({s.division}): {s.present_students}/{s.registered_students} present ({s.attendance_rate:.1f}%) -> {status}")

    print("\nGenerated Merge Recommendations:")
    for i, r in enumerate(recs, 1):
        print(f"\nRecommendation #{i}:")
        print(f"  Merged Sessions : {r.merged_session_ids} ({', '.join(r.combined_divisions)})")
        print(f"  Subject         : {r.subject}")
        print(f"  Target Room     : {r.target_room} (Capacity: {r.room_capacity})")
        print(f"  Combined Count  : {r.total_students} students")
        print(f"  Freed Room(s)   : {', '.join(r.freed_rooms)}")
        print(f"  Assigned Faculty: {r.assigned_faculty}")
        print(f"  Est. Energy Save: {r.energy_savings_kWh_est:.1f} kWh")

    print("\nNotifications Sent:")
    for category, msgs in notifs.items():
        for m in msgs:
            print(f" - {m}")

    print("="*70 + "\n")

    return {
        "recommendations": recs,
        "freed_rooms": freed_rooms,
        "notifications": notifs
    }

if __name__ == "__main__":
    run_demo_optimization()
